# TODO:
# - Test from an EE image since testing was local using a-core..
# - Create a role for file creation on NFS 
# - Update documentation
# - dynamic file name of some sort
#   - looping on file creations and/or directory creations in NFS
# - validate the fileshare permissions from the mounted volume in the 
#   EE Node OS.  Seems the 'awx' user needs 'rwx' perms to that newly
#   mounted volume/folder...  Double check this..

- name: Prepare NFS Connection for Execution Environment Nodes 
  hosts: all
  gather_facts: no

  collections: 
    - ansible.posix.mount

  tasks:
    - name: include role for preparing EE nodes
      include_role:
        name: nfs

    - name: include role for creating files/directories 
      include_role:
        name: nfs
        tasks_from: file-create.yml 


#    - name: List dir contents
#      command: | 
#          ls -l /ansible
#      register: dir_contents
#
#    - name: sleep for a while please 
#      pause:
#        minutes: "5"

