# TODO:
# - Create a role for file creation on NFS 
# - Update documentation
# - dynamic file name of some sort
#   - looping on file creations and/or directory creations in NFS
# - validate the fileshare permissions from the mounted volume in the 
#   EE Node OS.  Seems the 'awx' user needs 'rwx' perms to that newly
#   mounted volume/folder...  Double check this..

- name: Prepare NFS Connection for Execution Environment Nodes 
  hosts: execution_nodes
  gather_facts: no

  collections: 
    - ansible.posix.mount

  tasks:
    - name: include role for preparing EE nodes
      include_role:
        name: nfs

    - name: try the file module now
      file:
        path: "/ansible/dude-wtf-is-happening.txt"
        state: touch
        force: true
      register: touch_results

    - name: debug touch results 
      debug:
        msg: "{{ touch_results }}"

#    - name: List dir contents
#      command: | 
#          ls -l /ansible
#      register: dir_contents
#
#    - name: sleep for a while please 
#      pause:
#        minutes: "5"

