- name: Taking a stat of the '/' to see what volumes exist
  hosts: all

  vars:
    shared_volume_path: "/ansible/WTF-ITS-WORKING-AAP-yep-it-worked.crap"
    become_user: root
  
  tasks:
#    - name: lets go...
#      debug:
#        msg: "Hello World!"


    - name: create file and place in 'shared_volume_path' directory
      command: echo 'something - from aap' > "{{ shared_volume_path }}"
      register: echo_return

    - name: debug echo 
      debug:
        msg: "{{ echo_return }}"

    - name: sleep for a while please 
      pause:
        minutes: "5"
          #- name: try the file module now
          #  file:
          #    path: "{{ shared_volume_path }}" 
          #    state: touch
          #    force: true
          #  delegate_to: localhost
          #  become_user: true

          #    - name: List dir contents - ONE LAST TIME
          #      command: | 
          #          ls -l /ansible
          #      register: dir_contents
          ##      delegate_to: localhost
          #
          #    - name: Stat return register - ONE LAST TIME
          #      debug:
          #        var: "{{ dir_contents }}"
          ##       with_items: dir_contents
          #
