- name: Taking a stat of the '/' to see what volumes exist
  hosts: all
  become: true

  vars:
    shared_volume_path: "/ansible/{{ inventory_hostname }}"
    become_user: root
  
  tasks:
    - name: lets go...
      debug:
        msg: "{{ inventory_hostname }}"

    - name: List dir contents
      command: | 
         ls -al
      register: dir_contents

    - name: Stat return register
      debug:
        var: "{{ dir_contents }}"

    - name: List dir contents - ONE LAST TIME
      command: | 
         pwd
      register: working_dir

    - name: Stat return register - ONE LAST TIME
      debug:
        var: "{{ working_dir }}"
        #    - name: try the file module now
        #      file:
        #        path: "{{ shared_volume_path }}" 
        #        state: touch
        #        force: true
        #        follow: false
        #        owner: nobody
        #        group: nobody
        #        mode: '0777'
        #      delegate_to: localhost
        #        #  become_user: true
        #
        #    - name: List dir contents - ONE LAST TIME
        #      command: | 
        #          ls -l /ansible
        #      register: dir_contents
        #      delegate_to: localhost
        #
        #    - name: Stat return register - ONE LAST TIME
        #      debug:
        #        var: "{{ dir_contents }}"

    - name: sleep for a while please 
      pause:
        minutes: "5"
