- name: Taking a stat of the '/' to see what volumes exist
  hosts: all

  vars:
    shared_volume_path: "/ansible/WTF-ITS-WORKING-AAP-yep-it-worked.crap"
  
  tasks:
#    - name: lets go...
#      debug:
#        msg: "Hello World!"

    - name: List dir contents
      command: | 
          ls -l /
      register: dir_contents
      delegate_to: localhost
        
    - name: Stat return register
      debug:
        var: "{{ item }}"
      with_items: dir_contents.stdout_lines

    - name: create file and place in 'shared_volume_path' directory
      file:
        path: "{{ shared_volume_path }}" 
        state: touch
          #      delegate_to: localhost

    - name: List dir contents - ONE LAST TIME
      command: | 
          ls -l /ansible
      register: dir_contents_2
        #      delegate_to: localhost

    - name: Stat return register - ONE LAST TIME
      debug:
        var: "{{ item }}"
      with_items: dir_contents_2.stdout_lines
