
# TODO:
# - Create a role for file creation on NFS 
# - Update documentation
# - Why is localhost running on tasks delegated to [execution_nodes] inventory group
#   - hosts file messed up?
#

- name: Prepare NFS Connection for Execution Environment Nodes 
  hosts: all
  gather_facts: no

  collections: 
    - ansible.posix.mount

  tasks:
    - name: include role for preparing EE nodes
      include_role:
        name: nfs

    - name: try the file module now
      file:
        path: "/ansible/dude-wtf-is-happening.txt"
        state: touch
        force: true
      register: touch_results

    - name: debug touch results 
      debug:
        msg: "{{ touch_results }}"

#    - name: List dir contents
#      command: | 
#          ls -l /ansible
#      register: dir_contents
#
#    - name: sleep for a while please 
#      pause:
#        minutes: "5"

