- name: Taking a stat of the '/' to see what volumes exist
  hosts: all

  vars:
    shared_volume_path: "/ansible/WTF-ITS-WORKING-AAP-yep-it-worked.crap"
  
  tasks:
#    - name: lets go...
#      debug:
#        msg: "Hello World!"


    - name: create file and place in 'shared_volume_path' directory
      shell: |
         echo "something - from aap " > /ansible/cruddy-number-99.txt
      register: echo_return

    - name: debug echo 
      debug:
        msg: "{{ echo_return }}"

    - name: try the file module now
      file:
        path: "{{ shared_volume_path }}" 
        state: touch
        force: true
      delegate_to: localhost
      become_user: true

    - name: List dir contents - ONE LAST TIME
      command: | 
          ls -l /ansible
      register: dir_contents_2
        #      delegate_to: localhost

        #    - name: Stat return register - ONE LAST TIME
        #      debug:
        #        var: "{{ item }}"
        #      with_items: dir_contents_2.stdout_lines

    - name: sleep for a while please 
      pause:
        minutes: "5"
