all:
  children:
    execution_nodes:
      hosts:
        execnode1:
          ansible_host: 192.168.59.111
    control_nodes:
      hosts:
        localhost:
          ansible_connection: local
  vars:
    ansible_user: root 
      
#^^This had to be set for running from an OSX box - 
#ssh/ansible defaults with non-root user that may 
#or may not exist on the endpoint running things on.
