all:
  children:
    execution_nodes:
      hosts:
        execnode1:
          ansible_host: 192.168.59.111
#          ssh_user: root
#          become_method: su
#          become_user: root
          ansible_user: root
    control_nodes:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
  vars:
    #    ssh_user: root
#    become_method: su
#    become_user: root
    ansible_user: root
