---
# DEFAULT VARS

###################
#NFS Pre-requisites
################### 
#Yum/DNF packages required for mounting nfs volume(s)
nfs_packages: 
  - rpcbind
  - nfs-utils
  - showmount #for troubleshooting via commandline

##################
#NFS server info
################## 
nfs_server_address: 192.168.56.12 #"Ip.Add.Re.ss"
nfs_server_mount: "/mnt/nfs_shares/docs"
nfs_export_path: "{{ nfs_server_address }}:{{ nfs_server_mount }}"

##################
#Mount information
################## 
# CLI of Mount command
# "mount -t nfs 192.168.56.12:/mnt/nfs_shares/docs -o rw,sync,hard,context='system_u:object_r:container_file_t:s0' /ansible --make-shared"

# Variable`ized
# mount command: "mount -t {{ mount_type }} {{ nfs_server_path }} -o {{ nfs_mount_opts }} {{ nfs_shared_volume }} {{ mount_as_shared }}"

mount_state: "mounted"
mount_type: "nfs"

# TODO: need to verify where to put context if things don't work
nfs_mount_opts: "rw,sync,hard" # ,{{ nfs_selinux_context }}"
nfs_selinux_context: "context='system_u:object_r:container_file_t:s0'"

# TODO: need to verify. may not be a thing..
mount_as_shared: "--make-shared"

#################### 
# Volume information
#################### 
nfs_shared_volume: "/ansible"
shared_volume_file: "WTF-MATE-{{ 101 |random(start=1, step=10) }}.txt"
shared_full_path: "{{ nfs_shared_volume }}/{{ shared_volume_file }}"
